### ISSUE TITLE
can't run booklet-writer

### ISSUE THREAD

**Issue by taniaMashenko** [fsmosca/booklet-writer#3]
Hi Ferdinand,
I hope you are doing very well.
Could you please update the booklet-writer, it is not running with new Stockfish
Python 3.9

**Comment by fsmosca** [comment]
Which stockfish version did you use and which python chess module version?

I tried sf12 and sf14.1 and it worked.

### Typical setup guide in windows 10
* Create virtual environment folder venv to avoid conflict of module version.
 `python -m venv venv`
* Activate it
`./venv/scripts/activate`
* Install python-chess
`pip install python-chess==0.23.10` 

Then you can now execute the command line for example.
```
python booklet-writer.py --engine stockfish.exe --hash 128 --threads 1 --movetime 1000 --bmultipv 1 --wmultipv 4 --bookside black --inpgn sample.pgn
```

### Output
```
:: Settings ::
Book for                   : black
Move penalty for book side : -0.10
Minimum relative score     : -0.30
Max ply                    : 4
Movetime (ms)              : 1000
Hash (mb)                  : 128
Threads                    : 1

current pos:
rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2
Search at multipv = 4, movetime = 4s
1. d4 {scorecp: 52, depth: 18, rel_score: 0.00, penalty: 0.00}
1. Nf3 {scorecp: 30, depth: 18, rel_score: -0.22, penalty: 0.00}
1. Nc3 {scorecp: 22, depth: 18, rel_score: -0.30, penalty: 0.00}
1. c3 {scorecp: 6, depth: 18, rel_score: -0.46, penalty: 0.00}

move to extend next: 1. d4 {0.00}

current pos:
rnbqkbnr/pppp1ppp/4p3/8/3PP3/8/PPP2PPP/RNBQKBNR b KQkq - 0 2
Search at multipv = 1, movetime = 1s
1... d5 {scorecp: -39, depth: 19, rel_score: 0.00, penalty: -0.10}

move to extend next: 1... d5 {0.00}
...
```

**Comment by taniaMashenko** [comment]
Thank you very much Ferdinand,
I followed your instruction and it is working now
I used latest SF dev
God Bless you
